import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    ADMIN_EMAIL: z.string(),
    DATABASE_URL: z.string().url(),
    NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
    AWS_BUCKET_NAME: z.string().min(1),
    AWS_REGION: z.string().min(1),
    AWS_ACCESS_ID: z.string().min(1),
    AWS_SECRET: z.string().min(1),
    AUTH_RESEND_KEY: z.string(),
    OPENAI_API_KEY: z.string().min(1),
    STRIPE_PUBLISHABLE_KEY: z.string().min(1),
    STRIPE_SECRET_KEY: z.string().min(1),
    STRIPE_WEBHOOK_SECRET: z.string().min(1),
    VAPI_PRIVATE_KEY: z.string().min(1),
    VAPI_PRIVATE_KEY_UP_TO_29_JULY: z.string().min(1),
    VAPI_PRIVATE_KEY_UP_TO_27_JULY: z.string().min(1),
    VAPI_PRIVATE_KEY_UP_TO_17_JULY: z.string().min(1),
    VAPI_PRIVATE_KEY_UP_TO_11_JULY: z.string().min(1),
    VAPI_PRIVATE_KEY_UP_TO_04_JULY: z.string().min(1),
    TWITTER_CLIENT_SECRET: z.string().min(1),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string().url(),
    NEXT_PUBLIC_APP_NAME: z.string(),
    NEXT_PUBLIC_APP_DESCRIPTION: z.string(),
    NEXT_PUBLIC_VAPI_KEY: z.string().min(1),
    NEXT_PUBLIC_STRIPE_PRICE_ID_5: z.string().min(1),
    NEXT_PUBLIC_STRIPE_PRICE_ID_10: z.string().min(1),
    NEXT_PUBLIC_STRIPE_PRICE_ID_15: z.string().min(1),
    NEXT_PUBLIC_POSTHOG_KEY: z.string().min(1),
    NEXT_PUBLIC_POSTHOG_HOST: z.string().url(),
    NEXT_PUBLIC_TWITTER_CLIENT_ID: z.string().min(1),
    NEXT_PUBLIC_APP_SOCIAL_BANNER: z.string().url(),
  },
  runtimeEnv: {
    ADMIN_EMAIL: process.env.ADMIN_EMAIL,
    DATABASE_URL: process.env.DATABASE_URL,
    NODE_ENV: process.env.NODE_ENV,
    AWS_BUCKET_NAME: process.env.AWS_BUCKET_NAME,
    AWS_REGION: process.env.AWS_REGION,
    AWS_ACCESS_ID: process.env.AWS_ACCESS_ID,
    AWS_SECRET: process.env.AWS_SECRET,
    AUTH_RESEND_KEY: process.env.AUTH_RESEND_KEY,
    TWITTER_CLIENT_SECRET: process.env.TWITTER_CLIENT_SECRET,
    NEXT_PUBLIC_TWITTER_CLIENT_ID: process.env.NEXT_PUBLIC_TWITTER_CLIENT_ID,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    VAPI_PRIVATE_KEY: process.env.VAPI_PRIVATE_KEY_CURRENT,
    VAPI_PRIVATE_KEY_UP_TO_29_JULY: process.env.VAPI_PRIVATE_KEY_UP_TO_29_JULY,
    VAPI_PRIVATE_KEY_UP_TO_27_JULY: process.env.VAPI_PRIVATE_KEY_UP_TO_27_JULY,
    VAPI_PRIVATE_KEY_UP_TO_17_JULY: process.env.VAPI_PRIVATE_KEY_UP_TO_17_JULY,
    VAPI_PRIVATE_KEY_UP_TO_11_JULY: process.env.VAPI_PRIVATE_KEY_UP_TO_11_JULY,
    VAPI_PRIVATE_KEY_UP_TO_04_JULY: process.env.VAPI_PRIVATE_KEY_UP_TO_04_JULY,
    STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
    NEXT_PUBLIC_APP_DESCRIPTION: process.env.NEXT_PUBLIC_APP_DESCRIPTION,
    NEXT_PUBLIC_VAPI_KEY: process.env.NEXT_PUBLIC_VAPI_KEY,
    NEXT_PUBLIC_STRIPE_PRICE_ID_5: process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_5,
    NEXT_PUBLIC_STRIPE_PRICE_ID_10: process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_10,
    NEXT_PUBLIC_STRIPE_PRICE_ID_15: process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_15,
    NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
    NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
    NEXT_PUBLIC_APP_SOCIAL_BANNER: process.env.NEXT_PUBLIC_APP_SOCIAL_BANNER,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  emptyStringAsUndefined: true,
});
